opacity-rule = [
    "90:class_g *?= 'discord'",
    "97:class_g *?= 'firefox' && name *?='messenger'",
    "97:class_g *?= 'firefox' && name *?='twitter'",
    "90:class_g *?= 'firefox' && name *?='wikipedia'"
];

wintypes:
{
    dock = 
    {
        opacity = 0.75;
    };
};

