#!/usr/bin/perl

# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Licensed under the terms of the GNU GPL v3, or any later version.

use strict;
use warnings;
use utf8;

my $acpi;
my $percent;
my $ac_adapt;
my $status;
my $format;

# read the first line of the "acpi" command output
open (ACPI, "acpi -b 2>/dev/null| grep 'Battery 0' |") or die;
$acpi = <ACPI>;
close(ACPI);

# fail on unexpected output
if (not defined($acpi)) {
    # don't print anything to stderr if there is no battery
    exit(0);
}
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) {
	die "$acpi\n";
}

open (AC_ADAPTER, "acpi -a |") or die;
$ac_adapt = <AC_ADAPTER>;
close(AC_ADAPTER);

# get the percentage
$percent = $2;
if ($percent == 99) {$percent = 100;}

# determine status
if ($ac_adapt =~ /: ([\w-]+)/) {
    $ac_adapt = $1;

    if ($percent == 100 && $ac_adapt eq 'on-line') {
        $status = 'FULL '
    } elsif ($ac_adapt eq 'on-line') {
        $status = 'CHR ';
    } elsif ($ac_adapt eq 'off-line') {
        $status = 'BAT ';
    }
}

$format = " Bat: $percent% $status";

# time remaining
if ($acpi =~ /(\d\d:\d\d):/) {
	$format .= " ($1)";
}

# print text
print "$format\n";

exit(0);
