#!/bin/bash

# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

[[ ! -d /sys/class/net/wlp3s0/wireless ]] && exit
QUALITY=$(grep wlp3s0 /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')

# WiFi Off
if [[ "$(cat /sys/class/net/wlp3s0/operstate)" = 'down' ]]; then
    echo "off ❌"
    echo "off"
    echo "#ff367b"

# WiFi On
elif [[ "$(cat /sys/class/net/wlp3s0/operstate)" = 'up' ]]; then
    if [[ $QUALITY -ge 80 ]]; then
        echo "on" 
        echo "#46eb96"
    elif [[ $QUALITY -ge 60 ]]; then
        echo "on"
        echo "on" 
        echo "#6eb709"
    elif [[ $QUALITY -ge 40 ]]; then
        echo "on $QUALITY%" 
        echo "on"
        echo "#a5c600"
    fi
fi

