#!/bin/bash

startup=$SCRIPTS/startup_scripts

xinput -disable "ELAN Touchscreen"
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 1
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Click Method Enabled" {1 1}

source $startup/initial_wallpaper

