#!/bin/sh
case $1 in
    on)
        sudo rfkill unblock all
        echo "$(tput setaf 2)WiFi is now $1" 
        ;;
    off)
        sudo rfkill block all
        echo "$(tput setaf 1)WiFi is now $1"
        ;;
    *)
esac
